//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyWpfLoginNavigateExample.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.UserService")]
    public interface UserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/InsertUserDetails", ReplyAction="http://tempuri.org/UserService/InsertUserDetailsResponse")]
        bool InsertUserDetails(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/RegisterUser", ReplyAction="http://tempuri.org/UserService/RegisterUserResponse")]
        bool RegisterUser(string username, string password, string email, bool projectManager, bool scrumMaster, bool developer, string skillSet, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/checkUserDetails", ReplyAction="http://tempuri.org/UserService/checkUserDetailsResponse")]
        bool checkUserDetails(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/checkRegisteredUserDetails", ReplyAction="http://tempuri.org/UserService/checkRegisteredUserDetailsResponse")]
        bool checkRegisteredUserDetails(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/GetUserDetails", ReplyAction="http://tempuri.org/UserService/GetUserDetailsResponse")]
        SharedModelLibrary.UserModel GetUserDetails(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/getAllUsers", ReplyAction="http://tempuri.org/UserService/getAllUsersResponse")]
        SharedModelLibrary.UserModel[] getAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/searchUsers", ReplyAction="http://tempuri.org/UserService/searchUsersResponse")]
        SharedModelLibrary.UserModel[] searchUsers(string username, string email, string skillSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/ShowTeamMembersByProject", ReplyAction="http://tempuri.org/UserService/ShowTeamMembersByProjectResponse")]
        SharedModelLibrary.UserModel[] ShowTeamMembersByProject(string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/searchUserSkillset", ReplyAction="http://tempuri.org/UserService/searchUserSkillsetResponse")]
        SharedModelLibrary.UserModel[] searchUserSkillset(string skillset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/searchAvailableDevs", ReplyAction="http://tempuri.org/UserService/searchAvailableDevsResponse")]
        SharedModelLibrary.UserModel[] searchAvailableDevs(bool developer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserService/addImageToDatabase", ReplyAction="http://tempuri.org/UserService/addImageToDatabaseResponse")]
        bool addImageToDatabase(byte[] data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : EasyWpfLoginNavigateExample.ServiceReference.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<EasyWpfLoginNavigateExample.ServiceReference.UserService>, EasyWpfLoginNavigateExample.ServiceReference.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertUserDetails(string username, string password, string email) {
            return base.Channel.InsertUserDetails(username, password, email);
        }
        
        public bool RegisterUser(string username, string password, string email, bool projectManager, bool scrumMaster, bool developer, string skillSet, byte[] data) {
            return base.Channel.RegisterUser(username, password, email, projectManager, scrumMaster, developer, skillSet, data);
        }
        
        public bool checkUserDetails(string username, string password) {
            return base.Channel.checkUserDetails(username, password);
        }
        
        public bool checkRegisteredUserDetails(string email) {
            return base.Channel.checkRegisteredUserDetails(email);
        }
        
        public SharedModelLibrary.UserModel GetUserDetails(string username) {
            return base.Channel.GetUserDetails(username);
        }
        
        public SharedModelLibrary.UserModel[] getAllUsers() {
            return base.Channel.getAllUsers();
        }
        
        public SharedModelLibrary.UserModel[] searchUsers(string username, string email, string skillSet) {
            return base.Channel.searchUsers(username, email, skillSet);
        }
        
        public SharedModelLibrary.UserModel[] ShowTeamMembersByProject(string projectName) {
            return base.Channel.ShowTeamMembersByProject(projectName);
        }
        
        public SharedModelLibrary.UserModel[] searchUserSkillset(string skillset) {
            return base.Channel.searchUserSkillset(skillset);
        }
        
        public SharedModelLibrary.UserModel[] searchAvailableDevs(bool developer) {
            return base.Channel.searchAvailableDevs(developer);
        }
        
        public bool addImageToDatabase(byte[] data) {
            return base.Channel.addImageToDatabase(data);
        }
    }
}
